---
Paths:
  Reads: /scratch/mtblab/rachel/joint_EE_phage_R21/Environmental_Enteropathy_Viral_RdAB/bbtools_input
  Contaminants: /ref/lhlab/data/bbtools_databases/contaminants
  Host: /ref/lhlab/data/bbtools_databases/human_g1k/
  BlastX: /ref/lhlab/data/BLAST_VIRUS_DB/viroDB

Tools:
  BBTools: eval $( spack load --sh bbmap@38.63 )
  IDBA: /ref/mtblab/software/idba-1.1.3-longreads/idba-1.1.3/bin/
  BLAST: eval $( spack load --sh blast-plus@2.12.0 )
  MEGAN: /ref/lhlab/software/megan_ce_6_24_20/tools/ 

System:
  Memory: -Xmx32g
