---
Paths:
  Reads: /scratch/mtblab/rachel/R21_DA_Phage_EED/bbtools_approach/test_data
  Contaminants: /ref/lhlab/data/bbtools_databases/contaminants
  Host: /ref/lhlab/data/human_g1k/

Tools:
  BBTools: /ref/mtblab/software/bbmap_38.96/bbmap/
  IDBA: /ref/mtblab/software/idba-1.1.3-longreads/idba-1.1.3/bin/

System:
  Memory: -Xmx25g
