---
Paths:
  Reads: /scratch/mtblab/rachel/joint_EE_phage_R21/Environmental_Enteropathy_Viral_RdAB/archived
  Contaminants: /ref/lhlab/data/bbtools_databases/contaminants
  Host: /ref/lhlab/data/bbtools_databases/human_g1k/

Tools:
  BBTools: /ref/mtblab/software/bbmap_38.96/bbmap/
  IDBA: /ref/mtblab/software/idba-1.1.3-longreads/idba-1.1.3/bin/

System:
  Memory: -Xmx25g
